version: "3.7"

services:
    db:
        image: 'postgres:13.1-alpine'
        container_name: db
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
        ports:
            - 5432:5432
        volumes:
            - ./postgres-volume:/var/lib/postgresql/data

    cleverpy-backend-test:
        image: 'cleverpy-backend-test:latest'
        build:
            context: .
        container_name: cleverpy-backend-test
        ports:
            - 8080:8080
        depends_on:
            - db
        environment:
            SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/postgres
            SPRING_DATASOURCE_USERNAME: postgres
            SPRING_DATASOURCE_PASSWORD: postgres
            SPRING_JPA_HIBERNATE_DDL_AUTO: none
            APP.JWT.SECRET: 1234
volumes:
    postgres-volume:
