DROP TABLE IF EXISTS TIPO_PROGRAMADOR;
DROP TABLE IF EXISTS ROLES;
DROP TABLE IF EXISTS EMPLEADOS;
DROP TABLE IF EXISTS PELICULAS_SERIES;

CREATE TABLE TIPOS_PROGRAMADOR(
    ID SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(255) NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_DATE,
    FECHA_ACTUALIZACION TIMESTAMP DEFAULT CURRENT_DATE
);

CREATE TABLE ROLES(
    ID SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(255) NOT NULL,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_DATE,
    FECHA_ACTUALIZACION TIMESTAMP DEFAULT CURRENT_DATE
);

CREATE TABLE EMPLEADOS (
    ID SERIAL PRIMARY KEY,
    NOMBRE VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    ID_TIPO_PROGRAMADOR INTEGER,
    FECHA_NACIMIENTO DATE NOT NULL ,
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_DATE,
    FECHA_ACTUALIZACION TIMESTAMP DEFAULT CURRENT_DATE,
    ID_ROL INTEGER NOT NULL,
    FOREIGN KEY (ID_TIPO_PROGRAMADOR) REFERENCES TIPOS_PROGRAMADOR(ID),
    FOREIGN KEY (ID_ROL) REFERENCES ROLES(ID)
);

CREATE TABLE PELICULAS_SERIES (
    ID SERIAL PRIMARY KEY,
    TITULO VARCHAR(255) NOT NULL,
    ANIO INTEGER NOT NULL,
    DIRECTOR VARCHAR(255) NOT NULL,
    GENERO VARCHAR(50) NOT NULL,
    TEMPORADAS INTEGER,
    DURACION TIME,
    ID_EMPLEADO_PROPOSICION INTEGER,
    ID_EMPLEADO_IMPLANTACION INTEGER,
    NOTA_MEDIA DECIMAL(3, 1),
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_DATE,
    FECHA_ACTUALIZACION TIMESTAMP DEFAULT CURRENT_DATE,
    FOREIGN KEY (ID_EMPLEADO_PROPOSICION) REFERENCES EMPLEADOS(ID),
    FOREIGN KEY (ID_EMPLEADO_IMPLANTACION) REFERENCES EMPLEADOS(ID)
);
