DROP TABLE IF EXISTS PUNTUACIONES;

CREATE TABLE PUNTUACIONES (
    ID SERIAL PRIMARY KEY,
    ID_EMPLEADO INTEGER,
    ID_PELICULA_SERIE INTEGER,
    PUNTUACION DECIMAL(3, 1),
    FECHA_CREACION TIMESTAMP DEFAULT CURRENT_DATE,
    FECHA_ACTUALIZACION TIMESTAMP DEFAULT CURRENT_DATE,
    FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADOS(ID),
    FOREIGN KEY (ID_PELICULA_SERIE) REFERENCES PELICULAS_SERIES(ID),
    CONSTRAINT uk_ID_EMPLEADO_PELICULA_SERIE UNIQUE (ID_EMPLEADO, ID_PELICULA_SERIE)
);

-- Insertar algunas puntuaciones
INSERT INTO PUNTUACIONES (ID, ID_EMPLEADO, ID_PELICULA_SERIE, PUNTUACION) VALUES
(1, 1, 1, 8.5),
(2, 2, 2, 7.2),
(3, 3, 3, 9.0);

SELECT setval('cleverpy_test.puntuaciones_id_seq', (SELECT MAX(id) FROM puntuaciones e));


